#!/bin/bash

pushd $OPENSHIFT_REPO_DIR

# install newer npm
npm install npm@1.4.13

# create symlink to new npm version
mkdir -p "${OPENSHIFT_REPO_DIR}.node_modules/.bin"
npmpath=$(readlink -f ${OPENSHIFT_REPO_DIR}node_modules/.bin/npm)
ln -s "$npmpath" "${OPENSHIFT_HOMEDIR}.node_modules/.bin/npm"
hash -r

popd
